# Generated by Django 5.1.3 on 2024-11-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetUtilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('month', models.DateField(verbose_name='Month')),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Budget Amount')),
                ('spent_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Spent Amount')),
                ('utilization_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Utilization Percentage')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Budget Utilization',
                'verbose_name_plural': 'Budget Utilizations',
            },
        ),
        migrations.CreateModel(
            name='SpendingAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Amount')),
                ('transaction_count', models.PositiveIntegerField(verbose_name='Transaction Count')),
                ('average_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Average Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Spending Analytics',
                'verbose_name_plural': 'Spending Analytics',
            },
        ),
    ]
