# Generated by Django 5.1.3 on 2024-11-26 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetutilization',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_utilization', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spendinganalytics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='budgetutilization',
            index=models.Index(fields=['user', 'month'], name='analytics_b_user_id_672cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetutilization',
            index=models.Index(fields=['category'], name='analytics_b_categor_bf8fae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetutilization',
            unique_together={('user', 'category', 'month')},
        ),
        migrations.AddIndex(
            model_name='spendinganalytics',
            index=models.Index(fields=['user', 'date'], name='analytics_s_user_id_1be344_idx'),
        ),
        migrations.AddIndex(
            model_name='spendinganalytics',
            index=models.Index(fields=['category'], name='analytics_s_categor_02d7aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='spendinganalytics',
            unique_together={('user', 'date', 'category')},
        ),
    ]
