# Generated by Django 5.0.1 on 2024-12-12 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_alerts', models.BooleanField(default=True)),
                ('expense_alerts', models.BooleanField(default=True)),
                ('system_notifications', models.BooleanField(default=True)),
                ('reminders', models.BooleanField(default=True)),
                ('budget_exceeded_alerts', models.BooleanField(default=True)),
                ('recurring_expense_alerts', models.BooleanField(default=True)),
                ('threshold_alerts', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('notification_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='immediate', max_length=20)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('BUDGET_ALERT', 'Budget Alert'), ('EXPENSE_ALERT', 'Expense Alert'), ('SYSTEM', 'System Notification'), ('REMINDER', 'Reminder'), ('BUDGET_EXCEEDED', 'Budget Exceeded'), ('RECURRING_EXPENSE', 'Recurring Expense'), ('THRESHOLD_REACHED', 'Threshold Reached'), ('CUSTOM', 'Custom Notification')], default='SYSTEM', max_length=50, verbose_name='Type')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20, verbose_name='Priority')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('action_url', models.CharField(blank=True, help_text='URL for any action associated with this notification', max_length=255, verbose_name='Action URL')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional context for the notification', verbose_name='Additional Data')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this notification should expire', null=True, verbose_name='Expires At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
