# Generated by Django 5.1.3 on 2024-11-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('BUDGET_ALERT', 'Budget Alert'), ('EXPENSE_ALERT', 'Expense Alert'), ('SYSTEM', 'System Notification'), ('REMINDER', 'Reminder'), ('BUDGET_EXCEEDED', 'Budget Exceeded'), ('RECURRING_EXPENSE', 'Recurring Expense'), ('THRESHOLD_REACHED', 'Threshold Reached'), ('CUSTOM', 'Custom Notification')], default='SYSTEM', max_length=50, verbose_name='Type')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20, verbose_name='Priority')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('action_url', models.CharField(blank=True, help_text='URL for any action associated with this notification', max_length=255, verbose_name='Action URL')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional context for the notification', verbose_name='Additional Data')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this notification should expire', null=True, verbose_name='Expires At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email Notifications')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Push Notifications')),
                ('notification_types', models.JSONField(default=list, help_text='List of enabled notification types', verbose_name='Enabled Notification Types')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='Quiet Hours Start')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='Quiet Hours End')),
                ('minimum_priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='LOW', max_length=20, verbose_name='Minimum Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
