# Generated by Django 5.1.3 on 2024-11-26 18:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('category', models.CharField(choices=[('FOOD', 'Food & Dining'), ('TRANSPORT', 'Transportation'), ('HOUSING', 'Housing & Utilities'), ('HEALTHCARE', 'Healthcare'), ('ENTERTAINMENT', 'Entertainment'), ('SHOPPING', 'Shopping'), ('EDUCATION', 'Education'), ('OTHER', 'Other')], default='OTHER', max_length=100, verbose_name='Category')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('recurrence', models.CharField(choices=[('NONE', 'No Recurrence'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='NONE', max_length=10, verbose_name='Recurrence')),
                ('notification_threshold', models.DecimalField(decimal_places=2, default=80.0, help_text='Percentage at which to send notifications', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Notification Threshold')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code for the budget display', max_length=7, verbose_name='Color')),
                ('notes', models.JSONField(blank=True, default=dict, help_text='Additional metadata for the budget', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['-created_at'],
            },
        ),
    ]
