# Generated by Django 5.1.3 on 2024-11-26 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'category'], name='budgets_bud_user_id_c09b69_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['start_date', 'end_date'], name='budgets_bud_start_d_b133e8_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['is_active', 'recurrence'], name='budgets_bud_is_acti_13697b_idx'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(check=models.Q(end_date__gte=models.F('start_date')), name='budget_end_date_gte_start_date'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(check=models.Q(amount__gt=0), name='budget_amount_positive'),
        ),
    ]
