# Generated by Django 5.1.3 on 2024-11-26 18:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Percentage Share')),
                ('shares', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Shares')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Share Amount')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Amount Paid')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('last_reminded', models.DateTimeField(blank=True, null=True, verbose_name='Last Reminded')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Participant Share',
                'verbose_name_plural': 'Participant Shares',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Total Amount')),
                ('split_method', models.CharField(choices=[('EQUAL', 'Split Equally'), ('PERCENTAGE', 'Split by Percentage'), ('CUSTOM', 'Custom Split'), ('SHARES', 'Split by Shares')], default='EQUAL', max_length=20, verbose_name='Split Method')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SETTLED', 'Settled'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=20, verbose_name='Status')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('category', models.CharField(choices=[('FOOD', 'Food & Dining'), ('TRANSPORT', 'Transportation'), ('HOUSING', 'Housing & Utilities'), ('HEALTHCARE', 'Healthcare'), ('ENTERTAINMENT', 'Entertainment'), ('SHOPPING', 'Shopping'), ('EDUCATION', 'Education'), ('OTHER', 'Other')], default='OTHER', max_length=100, verbose_name='Category')),
                ('reminder_frequency', models.IntegerField(default=7, help_text='Frequency of payment reminders in days', verbose_name='Reminder Frequency (days)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'Shared Expense',
                'verbose_name_plural': 'Shared Expenses',
                'ordering': ['-created_at'],
            },
        ),
    ]
