# Generated by Django 5.1.3 on 2024-11-26 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0002_initial'),
        ('shared_expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participantshare',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_shares', to=settings.AUTH_USER_MODEL, verbose_name='Participant'),
        ),
        migrations.AddField(
            model_name='sharedexpense',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_shared_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='sharedexpense',
            name='expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_expense', to='expenses.expense', verbose_name='Related Expense'),
        ),
        migrations.AddField(
            model_name='participantshare',
            name='shared_expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_shares', to='shared_expenses.sharedexpense', verbose_name='Shared Expense'),
        ),
        migrations.AddIndex(
            model_name='sharedexpense',
            index=models.Index(fields=['creator', 'status'], name='shared_expe_creator_ef492a_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedexpense',
            index=models.Index(fields=['due_date'], name='shared_expe_due_dat_810690_idx'),
        ),
        migrations.AddIndex(
            model_name='participantshare',
            index=models.Index(fields=['shared_expense', 'participant'], name='shared_expe_shared__26ad59_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participantshare',
            unique_together={('shared_expense', 'participant')},
        ),
    ]
