# Generated by Django 5.0.1 on 2024-12-02 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
        ('shared_expenses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sharedexpense',
            name='shared_expe_due_dat_810690_idx',
        ),
        migrations.AddIndex(
            model_name='sharedexpense',
            index=models.Index(fields=['creator'], name='shared_expe_creator_0aa11b_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedexpense',
            index=models.Index(fields=['status'], name='shared_expe_status_91db0e_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedexpense',
            index=models.Index(fields=['created_at'], name='shared_expe_created_5d638e_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedexpense',
            index=models.Index(fields=['creator', 'created_at'], name='shared_expe_creator_424a64_idx'),
        ),
    ]
